import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Check, Copy, Eye, EyeOff, Globe, KeyRound, LogOut, Monitor, Moon, PanelsTopLeft, Search, Settings, ShieldCheck, Sun, SunMoon } from 'lucide-react';
import { Button, Modal, safeRead } from './ui.jsx';
import { NavLink, WorkspaceShell } from './navigation.jsx';

async function api(path, options) {
  const response = await fetch('/admin/api' + path, { cache: 'no-store', ...options });
  const result = response.status === 204 ? null : await response.json();
  if (!response.ok) throw Object.assign(new Error(result?.error || 'The admin request could not be completed.'), { status: response.status });
  return result;
}
const post = data => ({ method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
export default function AdminApp() {
  const [session, setSession] = useState(null), [error, setError] = useState(''), [route, setRoute] = useState(location.pathname), [appearance, setAppearance] = useState(false), [theme, setTheme] = useState(() => safeRead('commons-theme','system'));
  const heading = useRef();
  useEffect(() => { document.title = 'Server admin · Commons'; const pop = () => setRoute(location.pathname); addEventListener('popstate',pop); return () => removeEventListener('popstate',pop); }, []);
  useEffect(() => { const media = matchMedia('(prefers-color-scheme: dark)'); const apply = () => { document.documentElement.dataset.theme = theme === 'system' ? media.matches ? 'dark' : 'light' : theme; }; apply(); media.addEventListener('change',apply); try { localStorage.setItem('commons-theme',theme); } catch {} return () => media.removeEventListener('change',apply); },[theme]);
  const checkSession = async () => { setError(''); try { setSession(await api('/session')); } catch { setSession(null); setError('Couldn’t check admin sign-in. Try again.'); } };
  useEffect(() => { checkSession(); }, []);
  useEffect(() => {
    if (!session?.authenticated) return;
    const timer = setTimeout(() => { setSession({ enabled:true, authenticated:false }); setError('Your admin session expired. Sign in again to continue.'); }, Math.max(0,session.expiresAt-Date.now()));
    const visible = () => { if (document.visibilityState === 'visible') checkSession(); };
    document.addEventListener('visibilitychange',visible);
    window.addEventListener('pageshow',visible);
    return () => { clearTimeout(timer); document.removeEventListener('visibilitychange',visible); window.removeEventListener('pageshow',visible); };
  }, [session?.expiresAt,session?.authenticated]);
  const unauthorized = e => { if (e.status === 401) { setSession({ enabled:true, authenticated:false }); setError('Your admin session ended. Sign in again to continue.'); } };
  const go = path => { history.pushState({},'',path); setRoute(path); window.scrollTo(0,0); setTimeout(() => heading.current?.focus(),0); };
  const logout = async () => { try { await api('/logout',post({})); setSession({ enabled:true, authenticated:false }); setError(''); } catch (e) { setError('Couldn’t sign out. Try again.'); } };
  const sidebar = <><div className="sidebar-context"><p className="eyebrow">SERVER ADMIN</p><p>{location.host}</p></div><nav className="workspace-nav" aria-label="Admin navigation"><NavLink icon={PanelsTopLeft} href="/admin" active={route !== '/admin/settings'} onClick={e => { e.preventDefault(); go('/admin'); }}>Calendars</NavLink><NavLink icon={Settings} href="/admin/settings" active={route === '/admin/settings'} onClick={e => { e.preventDefault(); go('/admin/settings'); }}>Instance settings</NavLink></nav><div className="sidebar-bottom"><button className="workspace-nav-link" data-close-nav onClick={() => setAppearance(true)}><SunMoon size={20} />Appearance</button><button className="workspace-nav-link" data-close-nav onClick={logout}><LogOut size={20} />Sign out</button><p className="small muted">Server administrator</p></div></>;
  const selected = /^\/admin\/calendars\/([a-z0-9-]+)\/?$/.exec(route)?.[1];
  return <>{session?.authenticated ? <WorkspaceShell sidebar={sidebar} title="Commons admin" brandHref="/admin"><main id="main" ref={heading} tabIndex={-1} className="admin-main">{error && <p className="notice error-notice" role="alert">{error}</p>}{route === '/admin/settings' ? <AdminSettings onUnauthorized={unauthorized} /> : selected ? <CalendarAccess key={selected} id={selected} go={go} onUnauthorized={unauthorized} /> : <Directory go={go} onUnauthorized={unauthorized} />}</main></WorkspaceShell> : <main id="main" className="admin-login"><a className="text-link" href="/">Back to Commons <ArrowUpRight size={16}/></a><ShieldCheck size={34} className="accent"/><p className="eyebrow">SERVER ADMIN</p><h1>Admin sign-in</h1><p className="muted">Manage calendar access on {location.host}.</p>{error && <p className="notice error-notice" role="alert">{error}</p>}{!session ? error ? <Button onClick={checkSession}>Try again</Button> : <p role="status">Checking admin sign-in…</p> : !session.enabled ? <p className="notice">Admin sign-in has not been configured. Set the server’s ADMIN_PASSWORD_HASH to enable it.</p> : <Login onSuccess={s => { setSession(s); setError(''); go('/admin'); }} />}<p className="small muted">Use the server-admin password. Organizer links do not grant admin access.</p></main>}{appearance && <Modal title="Appearance" onClose={() => setAppearance(false)}><div className="choices">{[['system',Monitor,'Use device setting'],['light',Sun,'Light'],['dark',Moon,'Dark']].map(([v,Icon,label]) => <button key={v} aria-pressed={theme===v} className={theme===v?'selected':''} onClick={() => setTheme(v)}><Icon size={20}/><span>{label}</span>{theme===v&&<Check size={20}/>}</button>)}</div></Modal>}</>;
}
function Login({ onSuccess }) {
  const [password,setPassword] = useState(''), [error,setError] = useState(''), [pending,setPending] = useState(false); const lock=useRef(false);
  const submit = async e => { e.preventDefault(); if(lock.current)return;lock.current=true;setPending(true);setError('');try { const session=await api('/login',post({password}));setPassword('');onSuccess(session); } catch(e){setError(e.message);setPassword('');} finally{lock.current=false;setPending(false);} };
  return <form className="stack" onSubmit={submit}><div className="field"><label htmlFor="admin-password">Admin password</label><input id="admin-password" type="password" autoComplete="current-password" required maxLength={1024} value={password} onChange={e=>setPassword(e.target.value)} disabled={pending}/></div>{error&&<p role="alert" className="notice error-notice">{error}</p>}<Button type="submit" primary disabled={pending}>{pending?'Signing in…':'Sign in'}</Button></form>;
}
function Directory({go,onUnauthorized}) {
  const [calendars,setCalendars]=useState(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  useEffect(()=>{let alive=true;setError('');api('/calendars').then(d=>{if(alive)setCalendars(d.calendars);}).catch(e=>{if(alive){onUnauthorized(e);setError(e.message);}});return()=>{alive=false;};},[attempt]);
  const filtered=calendars?.filter(c=>`${c.name} ${location.origin}${c.viewPath}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <><div className="content-intro"><p className="eyebrow">YOUR COMMONS INSTANCE</p><h1>Calendars</h1><p>Find a calendar and recover its organizer link.</p></div><div className="field admin-search"><label htmlFor="calendar-search">Search calendars</label><div><Search size={20} aria-hidden="true"/><input id="calendar-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Calendar name or public URL" type="search"/></div></div>{error?<div role="alert" className="notice error-notice"><p>{error}</p><Button onClick={()=>setAttempt(a=>a+1)}>Try again</Button></div>:!calendars?<p role="status">Loading calendars…</p>:filtered.length?<><div className="admin-directory"><div className="admin-directory-head"><span>CALENDAR</span><span>ORGANIZER ACCESS</span><span className="sr-only">Action</span></div>{filtered.map(c=><article className="admin-directory-row" key={c.id}><div><h2>{c.name}</h2><p className="small muted">{location.host}{c.viewPath}</p></div><span className="muted small">{c.scopeCount===1?'This calendar only':`${c.scopeCount} calendars share access`}</span><a className="button" href={`/admin/calendars/${c.id}`} onClick={e=>{e.preventDefault();go(`/admin/calendars/${c.id}`);}}>View access <ArrowUpRight size={17}/></a></article>)}</div><p className="small muted" role="status">{filtered.length} of {calendars.length} calendars</p></>:<div className="empty"><h2>{calendars.length?'No matching calendars':'No calendars yet'}</h2><p>{calendars.length?'Try another calendar name or public URL.':'Calendars will appear here when they are configured or created.'}</p>{query&&<Button onClick={()=>setQuery('')}>Clear search</Button>}</div>}<div className="notice"><KeyRound size={23}/><p>Organizer links allow event and calendar changes. Check which calendars a link manages before sharing it.</p></div></>;
}
function CalendarAccess({id,go,onUnauthorized}) {
  const [data,setData]=useState(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[reveal,setReveal]=useState(false),[status,setStatus]=useState(''); const field=useRef();
  useEffect(()=>{let alive=true;setError('');api(`/calendars/${id}/access`).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive){onUnauthorized(e);setError(e.message);}});return()=>{alive=false;};},[id,attempt]);
  const copy=async(privateLink)=>{try{await navigator.clipboard.writeText(location.origin+(privateLink?data.workspacePath:data.viewPath));setStatus(privateLink?`Organizer link copied. It manages ${data.scope.length} calendar${data.scope.length===1?'':'s'}.`:'Public link copied.');}catch{setStatus('Copy was unavailable. Select and copy the link below.');if(privateLink){setReveal(true);setTimeout(()=>{field.current?.focus();field.current?.select();},0);}}};
  return <><button className="text-link back-link" onClick={()=>go('/admin')}><ArrowLeft size={17}/>Calendars</button>{error?<div role="alert"><p>{error}</p><Button onClick={()=>setAttempt(a=>a+1)}>Try again</Button></div>:!data?<p role="status">Loading calendar access…</p>:<><div className="content-intro"><h1>{data.name}</h1><p>Calendar access</p></div><section className="admin-access-panel"><h2><KeyRound size={24}/>Organizer link</h2><p className="muted">Anyone with this link can add, edit and delete events and change calendar settings.</p><div className="admin-scope"><p className="eyebrow">THIS LINK MANAGES {data.scope.length} CALENDAR{data.scope.length===1?'':'S'}</p><ul>{data.scope.map(c=><li key={c.id}>{c.name}</li>)}</ul></div><label htmlFor="organizer-url">Private organizer workspace URL</label><div className="copy-row private-link-row"><input id="organizer-url" ref={field} readOnly value={reveal?location.origin+data.workspacePath:location.origin+'/o/••••••••••••••••/'} onFocus={e=>{if(reveal)e.target.select();}}/><Button icon={reveal?EyeOff:Eye} aria-label={reveal?'Hide organizer link':'Reveal organizer link'} onClick={()=>setReveal(v=>!v)}/></div><div className="actions"><Button primary icon={Copy} onClick={()=>copy(true)}>Copy organizer link</Button><a href={data.workspacePath} target="_blank" rel="noopener noreferrer" className="button">Open workspace <ArrowUpRight size={18}/></a></div><p className="muted small">Share directly with a trusted organizer through your usual private channel.</p></section><section className="admin-access-panel public-access"><h2><Globe size={24}/>Public calendar link</h2><p className="muted">Anyone can view events. This link does not allow changes.</p><div className="copy-row"><input aria-label="Public calendar URL" readOnly value={location.origin+data.viewPath} onFocus={e=>e.target.select()}/><Button icon={Copy} onClick={()=>copy(false)}>Copy public link</Button></div></section>{status&&<p role="status" className="notice success-notice">{status}</p>}</>}</>;
}
function AdminSettings({onUnauthorized}) {
  const [settings,setSettings]=useState(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  useEffect(()=>{let alive=true;api('/settings').then(d=>{if(alive){setSettings(d);setError('');}}).catch(e=>{if(alive){onUnauthorized(e);setError(e.message);}});return()=>{alive=false;};},[attempt]);
  return <><div className="content-intro"><p className="eyebrow">SERVER ADMIN</p><h1>Instance settings</h1><p>Current configuration for {location.host}.</p></div>{error?<div role="alert"><p>{error}</p><Button onClick={()=>setAttempt(a=>a+1)}>Try again</Button></div>:!settings?<p role="status">Loading settings…</p>:<><dl className="admin-settings"><div><dt>New calendar creation</dt><dd>{settings.creationEnabled?'Enabled':'Disabled'}</dd></div><div><dt>Calendars</dt><dd>{settings.calendarCount}{settings.calendarLimit?` of ${settings.calendarLimit}`:''}</dd></div><div><dt>Admin session duration</dt><dd>{settings.sessionHours} hours</dd></div></dl><section className="note"><h2>Managed on the server</h2><p>Change signup availability, calendar limits or the admin password in the server configuration, then restart Commons. Restarting ends all admin sessions.</p></section></>}</>;
}
